version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # RAILS_ENV: 'development'
      # DATABASE_NAME: 'review_db'
      # DATABASE_SERVICE: 'db'
      # POSTGRES_USER: 'postgres'
      # POSTGRES_PASSWORD: 'postgres'
      BUNDLE_PATH: "/gems"
      RAILS_LOG_TO_STDOUT: "true"
      # SELENIUM_REMOTE_HOST: 'selenium'
    volumes:
      - .:/myapp
      - gems:/gems
    ports:
      - "3001:3001"
    command: bundle check || bundle install
    # command: ["sh", "bundle check || bundle install"]
  #   depends_on:
  #     - selenium
  # selenium:
  #   image: selenium/standalone-chrome
  #   container_name: selenium

volumes:
  gems:
#     external: true
